### ISSUE TITLE
Case insensitive commands?

### ISSUE THREAD

**Issue by Dncnsnwdn** [TheGeekOnSkates/breakaway-basic#1]
I know all-caps keywords are accurate to 8-bit BASICs, but having to switch Caps Lock on is a bit of a pain.

But actually, the real reason for opening this ticket is that I'm having to keep expenses to the minimum right now so I can't comment over at Lunduke's, and I just wanted to say, “This is awesome! Keep it up!” :)

**Comment by TheGeekOnSkates** [comment]
Hey @Dncnsnwdn,  thanks for the encouraging words and the constructive feedback.  I appreciate both. :smile: 

I get what you're saying about keeping expenses down... but at this point I spend way too much time on Lunduke's to give it up.  So much good stuff on there lol.  I've often said that "forums are my Facebook" and you can still find me on several... but his community has kind of replaced all of them except for NarniaWeb. :rofl:  

But anyway, let's talk about this issue you posted: You're right, all-caps instructions can be a pain, and I've often thought about changing it myself.  And I'm really glad you asked it.  It's gotten to where I want to name my scripts (and even other files/folders) using uppercase for that exact reason.  :rofl:

The problem with supporting lowercase commands is that (at least on Linux) most *external* commands are also lowercase.  Like for example, if you go to a terminal (not running Breakaway BASIC) and type print "some text", you'll get an error saying there is no file called "some text".  Lowercase "print" is a thing in Linux (apparently to print files to paper), which is why I've had to write my own PRINT instruction.   The same goes for the new ALIAS instruction I added earlier today (to the 0.3 branch).  This is also why I've hesitated to mess with porting to other platforms (like on DOS/Windows, everything is case-insensitive already anyway).

One solution might be to assume you mean the Breakaway BASIC command, and if you want to run the other one you'd have to use SYS.  And I think this might be where this goes by the time I get to 1.0.  The issue with doing it now is that there is no way to combine ("concatenate") strings, so SYS commands that require quotation marks wouldn't work.  It would have to support something like:

```
10 print "This would run Breakaway BASIC's print"
20 rem And this would run the Linux command, print "some file.txt"
30 sys "print " + chr$(34) + "some file.txt" + chr$(34)
```

I have this kind of string manipulation on my to-do list, so once that's done, *THEN* I think supporting lowercase commands might be doable.  I think just talking thru it "with you" (tho it has been pretty one-sided lol) has helped me answer how to make that work.  Thanks again! :smile:

Another thought: What about something like QB64 and the "Visual" brand of BASICs (VBScript, VBA, VB.NET etc.) where the first letter is in caps (what do they call that, PascalCase?)

```
10 Print "this might be a good short-term fix"
20 GoTo 10
```

Any thoughts on that?

**Comment by TheGeekOnSkates** [comment]
[@Dncnsnwdn](https://github.com/Dncnsnwdn) Hey again - you're good to go!  Just rolled out version 0.3, and all instructions/functions are now case-insensitive.  Of course system commands are not, but there's nothing I can do about that lol.

PS: Happy Friday! 😄
